apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablematch-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stablematch
  template:
    metadata:
      labels:
        app: stablematch
    spec:
      containers:
        - name: stablematch
          image: stablematch-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: stablematch-service
spec:
  type: NodePort
  selector:
    app: stablematch
  ports:
    - port: 8080
      targetPort: 8083
      nodePort: 30001